MONGODB_HOST: mongodb-{{ env }}.yaminiaws.fun
REDIS_HOST: redis-{{ env }}.yaminiaws.fun
CATALOGUE_HOST: catalogue-{{ env }}.yaminiaws.fun
CART_HOST: cart-{{ env }}.yaminiaws.fun
USER_HOST: user-{{ env }}.yaminiaws.fun
RABBITMQ_HOST: rabbitmq-{{ env }}.yaminiaws.fun
MYSQL_HOST: mysql-{{ env }}.yaminiaws.fun
SHIPPING_HOST: shipping-{{ env }}.yaminiaws.fun
PAYMENT_HOST: payment-{{ env }}.yaminiaws.fun