MONGODB_HOST: mongodb-{{ env }}.yaminiaws.fun
REDIS_HOST: redis-{{ env }}.yaminiaws.fun
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.yaminiaws.fun
CART_HOST: cart.backend-alb-{{ env }}.yaminiaws.fun
USER_HOST: user.backend-alb-{{ env }}.yaminiaws.fun
RABBITMQ_HOST: rabbitmq-{{ env }}.yaminiaws.fun
MYSQL_HOST: mysql-{{ env }}.yaminiaws.fun
SHIPPING_HOST: shipping.backend-alb-{{ env }}.yaminiaws.fun
PAYMENT_HOST: payment.backend-alb-{{ env }}.yaminiaws.fun